姓名:构建版本安装包

在……之上:
workflow_dispatch:

工作:
建立:
run-on:ubuntu-最新

步骤:
-姓名:签出代码
uses:操作/签出@v3

-姓名:设置JDK
uses:操作/设置-java@v3
和……一起:
分布:'祖鲁'
java版:'17'

-姓名:授予Gradle的执行权限
跑:chmod+x gradlew

-姓名:构建安装包
跑:./gradlew装配释放

-姓名:上传安装包
uses:操作/上载工件@v3
和……一起:
姓名:TVBox-APK
路径:app/build/outputs/apk/release/*.apk
